declare module "@carbon/themes" {
  export const interactive01: string;
  export const interactive02: string;
  export const interactive03: string;
  export const interactive04: string;
  export const uiBackground: string;
  export const ui01: string;
  export const ui02: string;
  export const ui03: string;
  export const ui04: string;
  export const ui05: string;
  export const text01: string;
  export const text02: string;
  export const text03: string;
  export const text04: string;
  export const text05: string;
  export const icon01: string;
  export const icon02: string;
  export const icon03: string;
  export const link01: string;
  export const inverseLink: string;
  export const field01: string;
  export const field02: string;
  export const inverse01: string;
  export const inverse02: string;
  export const support01: string;
  export const support02: string;
  export const support03: string;
  export const support04: string;
  export const inverseSupport01: string;
  export const inverseSupport02: string;
  export const inverseSupport03: string;
  export const inverseSupport04: string;
  export const overlay01: string;
  export const focus: string;
  export const hoverPrimary: string;
  export const activePrimary: string;
  export const hoverPrimaryText: string;
  export const hoverSecondary: string;
  export const activeSecondary: string;
  export const hoverTertiary: string;
  export const activeTertiary: string;
  export const hoverUI: string;
  export const activeUI: string;
  export const selectedUI: string;
  export const inverseHoverUI: string;
  export const hoverSelectedUI: string;
  export const hoverDanger: string;
  export const activeDanger: string;
  export const hoverRow: string;
  export const visitedLink: string;
  export const disabled01: string;
  export const disabled02: string;
  export const disabled03: string;
  export const highlight: string;
  export const skeleton01: string;
  export const skeleton02: string;
  export const brand01: string;
  export const brand02: string;
  export const brand03: string;
  export const active01: string;
  export const hoverField: string;

  export interface IColors {
    interactive01: string;
    interactive02: string;
    interactive03: string;
    interactive04: string;
    uiBackground: string;
    ui01: string;
    ui02: string;
    ui03: string;
    ui04: string;
    ui05: string;
    text01: string;
    text02: string;
    text03: string;
    text04: string;
    icon01: string;
    icon02: string;
    icon03: string;
    link01: string;
    inverseLink: string;
    field01: string;
    field02: string;
    inverse01: string;
    inverse02: string;
    support01: string;
    support02: string;
    support03: string;
    support04: string;
    inverseSupport01: string;
    inverseSupport02: string;
    inverseSupport03: string;
    inverseSupport04: string;
    overlay01: string;
    focus: string;
    hoverPrimary: string;
    activePrimary: string;
    hoverPrimaryText: string;
    hoverSecondary: string;
    activeSecondary: string;
    hoverTertiary: string;
    activeTertiary: string;
    hoverUI: string;
    activeUI: string;
    selectedUI: string;
    inverseHoverUI: string;
    hoverSelectedUI: string;
    hoverDanger: string;
    activeDanger: string;
    hoverRow: string;
    visitedLink: string;
    disabled01: string;
    disabled02: string;
    disabled03: string;
    highlight: string;
    skeleton01: string;
    skeleton02: string;
    brand01: string;
    brand02: string;
    brand03: string;
    active01: string;
    hoverField: string;
  }

  export const tokens: IColors;

  export const g10: IColors;
  export const g90: IColors;
  export const g100: IColors;
  export const white: IColors;
  export const v9: IColors;
  export const themes: {
    white: ITheme;
    g10: ITheme;
    g90: ITheme;
    g100: ITheme;
    v9: ITheme;
  };
}
